version: '3.8'

services:
  django:
    container_name: spy_cat_agency
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations
      && python manage.py makemigrations agency_tasks_app
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
